Traceback (most recent call last):
  File "/nfs/rs/psanjay/users/ztushar1/pytorch-stable-diffusion/sd/dm_diffusion.py", line 389, in <module>
    print(model(input_image_tensor,context,t).shape)
  File "/home/ztushar1/.conda/envs/df/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/ztushar1/.conda/envs/df/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/nfs/rs/psanjay/users/ztushar1/pytorch-stable-diffusion/sd/dm_diffusion.py", line 343, in forward
    output = self.unet(latent, context, time)
  File "/home/ztushar1/.conda/envs/df/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/ztushar1/.conda/envs/df/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/nfs/rs/psanjay/users/ztushar1/pytorch-stable-diffusion/sd/dm_diffusion.py", line 293, in forward
    x = layers(x, context, time)
  File "/home/ztushar1/.conda/envs/df/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/ztushar1/.conda/envs/df/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/nfs/rs/psanjay/users/ztushar1/pytorch-stable-diffusion/sd/dm_diffusion.py", line 189, in forward
    x = layer(x, context)
  File "/home/ztushar1/.conda/envs/df/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/ztushar1/.conda/envs/df/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/nfs/rs/psanjay/users/ztushar1/pytorch-stable-diffusion/sd/dm_diffusion.py", line 125, in forward
    x = self.attention_1(x)
  File "/home/ztushar1/.conda/envs/df/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/ztushar1/.conda/envs/df/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/nfs/rs/psanjay/users/ztushar1/pytorch-stable-diffusion/sd/attention.py", line 37, in forward
    weight = q @ k.transpose(-1, -2)
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 2048.00 GiB. GPU 0 has a total capacty of 23.64 GiB of which 14.97 GiB is free. Including non-PyTorch memory, this process has 8.67 GiB memory in use. Of the allocated memory 7.61 GiB is allocated by PyTorch, and 49.67 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
